import "./globals.css";
import { AuthProvider } from '@/contexts/AuthContext';
import { ThemeProvider } from '@/contexts/ThemeContext';
import { I18nProvider } from '@/contexts/I18nContext';
import { SchoolSettingsProvider } from '@/contexts/SchoolSettingsContext';
import { BrandProvider } from '@/contexts/BrandContext';
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata = {
  title: "School Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)} suppressHydrationWarning>
      <head>
        {/* Prevent flash of unstyled content — apply dark class before first paint */}
        <script dangerouslySetInnerHTML={{ __html: `
          try {
            var p = location.pathname;
            var isParent = p === '/parent' || p.indexOf('/parent/') === 0;
            var t = localStorage.getItem(isParent ? 'sms-parent-theme' : 'sms-theme') || 'system';
            var d = t === 'dark' || (t === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
            if (d) document.documentElement.classList.add('dark');
          } catch(e) {}
          try {
            var bc = JSON.parse(localStorage.getItem('sms-brand-colors') || 'null');
            if (bc && bc.primary) {
              document.documentElement.style.setProperty('--school-primary', bc.primary);
              document.documentElement.style.setProperty('--school-sidebar', bc.sidebar);
              document.documentElement.style.setProperty('--primary', bc.primary);
              document.documentElement.style.setProperty('--ring',    bc.primary);
            }
          } catch(e) {}
        `}} />
      </head>
      <body>
        <ThemeProvider>
          <I18nProvider>
            <AuthProvider>
              <BrandProvider>
                <SchoolSettingsProvider>
                  {children}
                </SchoolSettingsProvider>
              </BrandProvider>
            </AuthProvider>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
